_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.11.0rc1
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 54
                - 55
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 54
                - 55
            "3":
                - 23
                - 55
            "4": 3.11.0rc1
            "5": 0.18.3
            "6": 4.45.2
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
